### PR TITLE
Allow inputs from miner

### PR DESCRIPTION
**Pull request by Bathmat**
This allows inputs from the keyboard to work with the miner (such as 'h', 'c', 'r', etc.) without interfering with current logging setup.

### CODE REVIEW

**Comment by Bathmat** [comment]
Info was taken from here: https://nodejs.org/api/child_process.html#child_process_options_stdio

```
For convenience, options.stdio may be one of the following strings:

'pipe' - equivalent to ['pipe', 'pipe', 'pipe'] (the default)
'ignore' - equivalent to ['ignore', 'ignore', 'ignore']
'inherit' - equivalent to ['inherit', 'inherit', 'inherit'] or [0, 1, 2]
Otherwise, the value of options.stdio is an array where each index corresponds to an fd in the child. The fds 0, 1, and 2 correspond to stdin, stdout, and stderr, respectively. Additional fds can be specified to create additional pipes between the parent and child.
```

**Comment by MoneroOcean** [comment]
OK. Let me try that :)

**Comment by MoneroOcean** [comment]
Looks nice! However now, like I suspected I can not stop mm.js via Ctrl+C :)

**Comment by Bathmat** [comment]
Ctrl+c still works for me.

**Comment by MoneroOcean** [comment]
On Linux?

**Comment by Bathmat** [comment]
On windows, but yeah, Ctrl+c now just restarts the miner.

**Comment by MoneroOcean** [comment]
Added this functionality under new --miner_stdin option, so miner can decide if they want it

**Pull request merged**
